minimumReleaseAge: 0

minimumReleaseAgeExclude: null

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - lmdb
  - msgpackr-extract

pnpm:
  overrides:
    undici: '>=7.18.2'
    qs: '>=6.14.1'
    tar: '>=7.5.3'
